kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  #creating mysql in expense namespace
  namespace: expense
  #thus labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: backend
      tier: app
      project: expense
  #pod defintion
  template:
    metadata:
      labels:
        component: backend
        tier: app
        project: expense
    spec:
    - name: backend
      image: guru1188/backend:v1.0

------
# for connection mysql and backend pods we need to ensure to include a service which will helps in communication between pods i.,e Cluster IP
# This service is used to call mysql Pod
apiVersion: v1
kind: Service
metadata: 
  name: backend
  #attaching to expense namespace
  namespace: expense
spec: 
  selectors:
    project: expense
    component: frontend
    tier: app
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    