# a configMap is used to store non-confidential data in key-value pairs.
# This will helps in connecting to db-host from backend i..e ensuring connection to db
kind: configMap
apiVersion: v1
metadata: 
  name: backend
  namespace: expense
data:
  DB_HOST: mysql #mysql service component service name
--------
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  #creating mysql in expense namespace
  namespace: expense
  #thus labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: backend
      tier: app
      project: expense
  #pod defintion
  template:
    metadata:
      labels:
        component: backend
        tier: app
        project: expense
    spec:
      initContainers: #run before the main containers run, if initcontainers fail then main containers will not run
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 2; done"]
      containers:
      - name: backend
        image: guru1188/backend:v1.0
        # our backend server will run on http port 8080
        livenessProbe: #checking health of backend server for a period of time, if it fails then it will restart the server
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2 #how many times should it check for server failure, if it fails then restart will be done
          periodSeconds: 5 #for every 5 sec it will health check
          initialDelaySeconds: 30
        readinessProbe: #checking health of backend server for a period of time, if it fails then it will restart the server
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2 #how many times should it check for server failure, if it fails then restart will be done
          periodSeconds: 5 #for every 5 sec it will health check
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
            name: backend #your backend configmap name


------
# for connection mysql and backend pods we need to ensure to include a service which will helps in communication between pods i.,e Cluster IP
# This service is used to call backend Pod, by using selectors of backend pod
apiVersion: v1
kind: Service
metadata: 
  name: backend
  #attaching to expense namespace
  namespace: expense
spec: 
  selectors:
    project: expense
    component: backend
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    